version: 0.0
os: linux
files:
  - source: build/libs/aws_loadbalancer.war
    destination: /opt/tomcat/webapps/
hooks:
  ApplicationStop:
    - location: deregister_from_elb.sh
      runas: root
  ApplicationStart:
    - location: register_with_elb.sh
      runas: root